# src/AppBundle/Resources/config/validation.yml
AppBundle\Entity\User:
    #group_sequence:
        #- User
        #- Strict
    #getters:
        #passwordLegal:
            #- 'IsTrue':
                #message: 'The password cannot match your username'
                #groups: [Strict]
    properties:
        #username:
            #- NotBlank: ~
            #- Length:
            #    min: 3
        #password:
            #- NotBlank: ~
            #- Type: \Password
                #- Length:
                #    min: 3
        #Email:
            #- NotBlank: ~
            #- Type: \Email
        rol:
            #- NotBlank: ~
            - Choice:
                choices:  [Web-admin, CEO, Community-manager]
                message:  Choose a valid rol: [Web-admin, CEO, Community-manager]

