AppBundle\Entity\Post:
    type: entity
    repositoryClass: AppBundle\Entity\PostRepository
    table: post
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: bigint
            nullable: false
            unsigned: true
        description:
            type: text
            nullable: false
            length: 65535
            fixed: false
        userId:
            type: integer
            nullable: false
            unsigned: true
            column: user_id
        manyToOne:
            fk_userId:
                targetEntity: AppBundle\Entity\User
                joinColumn:
                    name: userId
                    referencedColumnName: id
                    nullable: false
    lifecycleCallbacks: {  }
