AppBundle\Entity\Rol:
    type: entity
    table: rol
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        webAdmin:
            type: integer
            nullable: false
            unsigned: false
            column: web-admin
        ceo:
            type: integer
            nullable: false
            unsigned: false
            column: CEO
        communityManager:
            type: integer
            nullable: false
            unsigned: false
            column: community_manager
    lifecycleCallbacks: {  }
